In [396]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

## Reading in the data

In [398]:
df = pd.read_csv('Food_Inspections_20250420.csv')

## Inspecting the data

In [400]:
df.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,1170324,CAPTAIN HOOKS FISH & CHICKEN/FIREHOUSE GRILL,CAPTAIN HOOKS FISH & CHICKEN FIREHOUSE GRILL,1804138.0,Restaurant,Risk 1 (High),5648 W ROOSEVELT,CHICAGO,IL,60644.0,06/18/2012,Complaint,Pass w/ Conditions,21. * CERTIFIED FOOD MANAGER ON SITE WHEN POTE...,41.865679,-87.766331,"(41.86567851033532, -87.76633113301574)"
1,2614750,CHICK-FIL-A PULLMAN,CHICK-FIL-A PULLMAN,3015728.0,Restaurant,Risk 1 (High),11131 S CORLISS AVE,CHICAGO,IL,60628.0,03/31/2025,License,Pass,58. ALLERGEN TRAINING AS REQUIRED - Comments: ...,41.691956,-87.600558,"(41.69195600663339, -87.60055824712973)"
2,2609909,HAPPY MARKET,HAPPY MARKET,2912802.0,Grocery Store,Risk 2 (Medium),2334 S WENTWORTH AVE,CHICAGO,IL,60616.0,01/02/2025,Canvass,Pass w/ Conditions,2. CITY OF CHICAGO FOOD SERVICE SANITATION CER...,41.849954,-87.632094,"(41.84995400192252, -87.63209419559098)"
3,2609927,SAT KAIVAL FOOD INC/SUBWAY,SAT KAIVAL FOOD INC/SUBWAY,2728400.0,Restaurant,Risk 1 (High),1916 S STATE ST,CHICAGO,IL,60616.0,01/02/2025,Canvass,Pass,36. THERMOMETERS PROVIDED & ACCURATE - Comment...,41.856053,-87.627311,"(41.85605269621059, -87.62731125804903)"
4,2615511,MAPLEWOOD BREWING COMPANY,MAPLEWOOD BREWING COMPANY,3016105.0,Liquor,Risk 3 (Low),2717-2719 N MAPLEWOOD AVE,CHICAGO,IL,60647.0,04/10/2025,License,Pass,56. ADEQUATE VENTILATION & LIGHTING; DESIGNATE...,41.930957,-87.691376,"(41.93095692249829, -87.69137628601092)"

In [401]:
df.describe()

,Inspection ID,License #,Zip,Latitude,Longitude
count,2.901050e+05,2.900870e+05,290066.000000,289113.000000,289113.000000
mean,1.797596e+06,1.760646e+06,60628.650711,41.880681,-87.676360
std,7.293276e+05,9.368612e+05,154.680103,0.081047,0.058378
min,4.424700e+04,0.000000e+00,10014.000000,41.644670,-87.906874
25%,1.335251e+06,1.381466e+06,60614.000000,41.831724,-87.707649
50%,1.982724e+06,2.073555e+06,60625.000000,41.891797,-87.666369
75%,2.492906e+06,2.417850e+06,60643.000000,41.939768,-87.634874
max,2.616045e+06,9.999999e+06,90504.000000,42.021064,-87.525094

In [402]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290105 entries, 0 to 290104
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Inspection ID    290105 non-null  int64
 1   DBA Name         290105 non-null  object
 2   AKA Name         287683 non-null  object
 3   License #        290087 non-null  float64
 4   Facility Type    284899 non-null  object
 5   Risk             290024 non-null  object
 6   Address          290105 non-null  object
 7   City             289946 non-null  object
 8   State            290047 non-null  object
 9   Zip              290066 non-null  float64
 10  Inspection Date  290105 non-null  object
 11  Inspection Type  290104 non-null  object
 12  Results          290105 non-null  object
 13  Violations       209581 non-null  object
 14  Latitude         289113 non-null  float64
 15  Longitude        289113 non-null  float64
 16  Location         289113 non-null  object
dtypes: float64(4), int64(1), object(12)
memory usage: 37.6+ MB

In [403]:
df.isna().sum()

Inspection ID          0
DBA Name               0
AKA Name            2422
License #             18
Facility Type       5206
Risk                  81
Address                0
City                 159
State                 58
Zip                   39
Inspection Date        0
Inspection Type        1
Results                0
Violations         80524
Latitude             992
Longitude            992
Location             992
dtype: int64

In [404]:
# Converting inspection date to datetime
df['Inspection Date'] = pd.to_datetime(df['Inspection Date'], errors='coerce')

In [405]:
df['Inspection Date'].dtypes

dtype('<M8[ns]')

### Column conversions

In [407]:
df['License #'] = df['License #'].astype('Int64').astype(str)
df['Zip'] = df['Zip'].astype('Int64').astype(str)

In [408]:
# Converting all columns to lowercase
df.columns = df.columns.str.lower().str.replace(' ', '_')
print(df.columns.tolist())

['inspection_id', 'dba_name', 'aka_name', 'license_#', 'facility_type', 'risk', 'address', 'city', 'state', 'zip', 'inspection_date', 'inspection_type', 'results', 'violations', 'latitude', 'longitude', 'location']

In [409]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290105 entries, 0 to 290104
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   inspection_id    290105 non-null  int64
 1   dba_name         290105 non-null  object
 2   aka_name         287683 non-null  object
 3   license_#        290105 non-null  object
 4   facility_type    284899 non-null  object
 5   risk             290024 non-null  object
 6   address          290105 non-null  object
 7   city             289946 non-null  object
 8   state            290047 non-null  object
 9   zip              290105 non-null  object
 10  inspection_date  290105 non-null  datetime64[ns]
 11  inspection_type  290104 non-null  object
 12  results          290105 non-null  object
 13  violations       209581 non-null  object
 14  latitude         289113 non-null  float64
 15  longitude        289113 non-null  float64
 16  location         289113 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(13)
memory usage: 37.6+ MB

In [410]:
df[['zip', 'license_#']].isna().sum()

zip          0
license_#    0
dtype: int64

### Accessing missing values

In [412]:
df.isna().sum().sort_values(ascending=False).head(10)

violations         80524
facility_type       5206
aka_name            2422
location             992
longitude            992
latitude             992
city                 159
risk                  81
state                 58
inspection_type        1
dtype: int64

### Exploring missing violations

In [414]:
# Investigating what inspection results are associated with missing violations.
df[df['violations'].isna()]['results'].value_counts()

results
Pass                    36526
Out of Business         24161
No Entry                11560
Not Ready                3790
Fail                     3535
Pass w/ Conditions        860
Business Not Located       92
Name: count, dtype: int64

In [415]:
# List of all the results only for inspections where violations are missing.

df[df['violations'].isna()]['results'].value_counts()

results
Pass                    36526
Out of Business         24161
No Entry                11560
Not Ready                3790
Fail                     3535
Pass w/ Conditions        860
Business Not Located       92
Name: count, dtype: int64

In [416]:
#Creating new column
df['has_violations'] = df['violations'].notna()
df['has_violations'].value_counts()

has_violations
True     209581
False     80524
Name: count, dtype: int64

In [417]:
df.isna().sum().sort_values(ascending=False)

violations         80524
facility_type       5206
aka_name            2422
location             992
longitude            992
latitude             992
city                 159
risk                  81
state                 58
inspection_type        1
inspection_id          0
results                0
zip                    0
inspection_date        0
dba_name               0
address                0
license_#              0
has_violations         0
dtype: int64

### Exploring missing facility types

In [419]:
# List of AKA names for rows where facility type is missing (to identify patterns).
df[df['facility_type'].isna()]['aka_name'].value_counts()

aka_name
SUBWAY                         35
DUNKIN DONUTS                  18
7-ELEVEN                       18
WHITE HEN PANTRY               17
MIDWEST BUDDHIST TEMPLE        15
                               ..
LA JALISCIENCE                  1
LIFE LINE TROPICAL JUICE        1
BLUE                            1
MERLE'S COFFEE SHOPPE, INC.     1
SIP & SAVOR COFFEE HOUSE        1
Name: count, Length: 4175, dtype: int64

### Filling Missing Facility Types Based on Known Business Names

* To impute missing `facility_type` values, I first reviewed the most common `aka_name` values among those rows. This revealed well-known chains such as SUBWAY, 7-ELEVEN, and DUNKIN DONUTS, where the expected facility type was clear.

* Based on these insights, I created a mapping dictionary to assign the most likely `facility_type` to these businesses. Remaining missing values were filled with `'Unknown'`.

In [421]:
# Filling missing facility types by mapping known AKA names to their most likely category

known_facility_types = {
    '7-ELEVEN': 'Grocery Store',
    'SUBWAY': 'Restaurant',
    'DUNKIN DONUTS': 'Restaurant',
    'WHITE HEN PANTRY': 'Grocery Store',
    'MIDWEST BUDDHIST TEMPLE': 'Religious Organization'
    
}

In [422]:
# Filling missing facility types by mapping known aka_names using the dictionary created earlier.
mask = df['facility_type'].isna()
df.loc[mask, 'facility_type'] = df.loc[mask, 'aka_name'].map(known_facility_types)

In [423]:
# Filling remaining missing facility types with unknown
df['facility_type'] = df['facility_type'].fillna('Unknown')

In [424]:
df['facility_type'].value_counts().head(10)

facility_type
Restaurant                         195863
Grocery Store                       35498
School                              18333
Children's Services Facility         6709
Unknown                              5103
Bakery                               4188
Daycare Above and Under 2 Years      3834
Daycare (2 - 6 Years)                3164
Long Term Care                       2208
Catering                             1795
Name: count, dtype: int64

In [425]:
df.isna().sum()

inspection_id          0
dba_name               0
aka_name            2422
license_#              0
facility_type          0
risk                  81
address                0
city                 159
state                 58
zip                    0
inspection_date        0
inspection_type        1
results                0
violations         80524
latitude             992
longitude            992
location             992
has_violations         0
dtype: int64

### Interpreting the risk column:
* Risk 1 (High): Higher likelihood of affecting public health

* Examples: restaurants, delis, schools

* Risk 2 (Medium): Moderate risk

* Examples: grocery stores, bakeries

* Risk 3 (Low): Lower risk

* Examples: warehouses, gas stations, vending machines

In [427]:
# Investigating mssing risk values
df['risk'].value_counts(dropna=False)

risk
Risk 1 (High)      214192
Risk 2 (Medium)     52668
Risk 3 (Low)        23094
NaN                    81
All                    70
Name: count, dtype: int64

In [428]:
# Viewing overall risk distribution by facility type to identify dominant risk levels.
df.groupby('facility_type')['risk'].value_counts(normalize=True).unstack().fillna(0).style.format("{:.0%}")

In [429]:
# Checking risk distribution for facility types with missing risk values to guide imputation strategy.
top_missing_types = df[df['risk'].isna()]['facility_type'].value_counts().index.tolist()

df[df['facility_type'].isin(top_missing_types)].groupby('facility_type')['risk'].value_counts(normalize=True).unstack().fillna(0).style.format("{:.0%}")

In [430]:
# These facility types were chosen because they appeared most frequently among rows with missing risk values
# And had a strong majority (typically over 70%) mapped to a specific risk level.
# This allows for confident imputation without introducing bias.

risk_by_facility = {
    'Restaurant':'Risk 1 (Hight)',
    'AFTER SCHOOL PROGRAM':'Risk 2 (Medium)',
    'CHURCH':'Risk 2 (Medium)',
    'Illegal Vendor':'Risk 3 (Low)',
    'Mobile Food Dispensor':'Risk 3 (Low)',
    'RETAIL':'Risk 3 (Low)',
    'Unknown':'Risk 3 (Low)', # for facility_type == 'Unknown'
    'WAREHOUSE':'Risk 1 (High)',
    'Wholesale':'Unknown'
}

In [431]:
# Filling missing risk values based on most common risk level for each facility type.
missing_risk_mask = df['risk'].isna()
df.loc[missing_risk_mask, 'risk'] = df.loc[missing_risk_mask, 'facility_type'].map(risk_by_facility)

In [432]:
#Assigning remaining missing risks with unknown
df['risk'] = df['risk'].fillna('Unknown Risk')

In [433]:
df.isna().sum()

inspection_id          0
dba_name               0
aka_name            2422
license_#              0
facility_type          0
risk                   0
address                0
city                 159
state                 58
zip                    0
inspection_date        0
inspection_type        1
results                0
violations         80524
latitude             992
longitude            992
location             992
has_violations         0
dtype: int64

### Filling missing aka_name with dba_name (doing business as)

In [435]:
df['aka_name'] = df['aka_name'].fillna(df['dba_name'])

In [436]:
df.isna().sum()

inspection_id          0
dba_name               0
aka_name               0
license_#              0
facility_type          0
risk                   0
address                0
city                 159
state                 58
zip                    0
inspection_date        0
inspection_type        1
results                0
violations         80524
latitude             992
longitude            992
location             992
has_violations         0
dtype: int64

### Accessing missing city and state rows

In [438]:
df['state'].value_counts()

state
IL    290032
IN        10
CA         2
CO         1
NY         1
WI         1
Name: count, dtype: int64

In [439]:
df['city'].value_counts()

city
CHICAGO         288968
Chicago            453
chicago            150
CCHICAGO            60
SCHAUMBURG          28
                 ...
ALGONQUIN            1
GRIFFITH             1
NEW YORK             1
NEW HOLSTEIN         1
GRAYSLAKE            1
Name: count, Length: 86, dtype: int64

In [440]:
# Capitalizing CHICAGO for consistency and removing known typo's
df['city'] = df['city'].str.upper().str.strip()
df['city'] = df['city'].replace({'CCHICAGO': 'CHICAGO'})

In [492]:
#If city and state is IL then it is almost certainly chicago
df.loc[df['city'].isna() & (df['state'] == 'IL'), 'city'] = 'CHICAGO'

# Fill state if city is CHICAGO
df.loc[df['state'].isna() & (df['city'] == 'CHICAGO'), 'state'] = 'IL'

In [494]:
df[['city', 'state']].isna().sum()

city     17
state    17
dtype: int64

In [496]:
df[df['city'].isna() & df['state'].isna()]['zip'].value_counts()

zip
60642    17
Name: count, dtype: int64

In [498]:
# Safely filling missing city and state values for rows with ZIP 60642
df.loc[(df['zip'] == '60642') & (df['city'].isna()), 'city'] = 'CHICAGO'
df.loc[(df['zip'] == '60642') & (df['state'].isna()), 'state'] = 'IL'

In [500]:
df.isna().sum()

inspection_id          0
dba_name               0
aka_name               0
license_#              0
facility_type          0
risk                   0
address                0
city                   0
state                  0
zip                    0
inspection_date        0
inspection_type        0
results                0
violations         80523
latitude             992
longitude            992
location             992
has_violations         0
dtype: int64

In [382]:
df[df['inspection_type'].isna()]

,inspection_id,dba_name,aka_name,license_#,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location,has_violations
162132,1946612,ARAMARL-FRESHII,FRESHII,2470318,Restaurant,Risk 1 (High),2650 N CLARK ST,CHICAGO,IL,60614,2016-07-14,NaN,Pass,NaN,41.930833,-87.644135,"(41.93083301378749, -87.64413543645641)",False

In [482]:
# Dropping the single row under inspection type that also has missing results and violations, likley an error in data collection
df = df[df['inspection_type'].notna()]

In [484]:
df.isna().sum()

inspection_id          0
dba_name               0
aka_name               0
license_#              0
facility_type          0
risk                   0
address                0
city                  17
state                 17
zip                    0
inspection_date        0
inspection_type        0
results                0
violations         80523
latitude             992
longitude            992
location             992
has_violations         0
dtype: int64

In [502]:
import os
os.getcwd()

'/Users/michaelashley/Documents/Coding-Temple/Module-6/Independant Project'

In [516]:
df.to_csv('cleaned_chicago_food_inspection_V1.csv', index = False)